// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHafLz0YNM3hQg2C2j7HYbHHZ-Y3X6cG0',
    appId: '1:903059244415:web:2b75d1c15b76a4bd0d464a',
    messagingSenderId: '903059244415',
    projectId: 'ondamenu-3dc99',
    authDomain: 'ondamenu-3dc99.firebaseapp.com',
    storageBucket: 'ondamenu-3dc99.appspot.com',
    measurementId: 'G-1CCV8H9S7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTY2xHnynDXGTYcTOOacO9xi2D-PdX124',
    appId: '1:903059244415:android:a1f26dd4f697c1bc0d464a',
    messagingSenderId: '903059244415',
    projectId: 'ondamenu-3dc99',
    storageBucket: 'ondamenu-3dc99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_swJBlkooy4geor_8RkvFK_NKxNhPWA',
    appId: '1:903059244415:ios:592bf63101ff3c640d464a',
    messagingSenderId: '903059244415',
    projectId: 'ondamenu-3dc99',
    storageBucket: 'ondamenu-3dc99.appspot.com',
    iosBundleId: 'com.ondamenu.ondamenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_swJBlkooy4geor_8RkvFK_NKxNhPWA',
    appId: '1:903059244415:ios:39800c2df61dfcc60d464a',
    messagingSenderId: '903059244415',
    projectId: 'ondamenu-3dc99',
    storageBucket: 'ondamenu-3dc99.appspot.com',
    iosBundleId: 'com.ondamenu.ondamenu.RunnerTests',
  );
}
